version: '3.8'
services:
  snipeit:
    depends_on:
      - snipeit_mysql
    image: snipe/snipe-it:v6.1.2
    container_name: snipeit
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - snipeit_data:/var/lib/snipeit
    ports:
      - "${SNIPE_IT_EXTERNAL_PORT}:${SNIPE_IT_INTERNAL_PORT}"
    env_file:
      - .env
  snipeit_mysql:
    container_name: ${MYSQL_HOST}
    volumes:
      - mysql_data:/var/lib/mysql
    image: mysql:8.1.0
    restart: always
    ports:
      - "3306:${MYSQL_PORT}"
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  snipeit_data:
  mysql_data: